name: Validar API Web .NET

# O robô vai rodar sempre que houver push na branch main
on:
  push:
    branches: [ "main" ]

jobs:
  build-api:
    # Mudamos para Linux (Ubuntu), que inicia e roda muito mais rápido
    runs-on: ubuntu-latest 

    steps:
    # Passo 1: Baixa o código da API para a máquina do GitHub
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    # Passo 2: Instala o SDK do .NET
    - name: Configurar o ambiente .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0 # Ajuste para a versão da sua API (ex: 6.0, 7.0, 8.0)

    # Passo 3: Restaura os pacotes NuGet da sua API
    - name: Restaurar dependências (NuGet)
      run: dotnet restore

    # Passo 4: Compila a API Web
    - name: Compilar a API Web (Build)
      run: dotnet build --no-restore --configuration Release
